name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  typecheck:
    uses: ./.github/workflows/type-check.yml

